### ISSUE TITLE
Cannot login in another pc

### ISSUE THREAD

**Issue by il-palmi** [SeraphJACK/SimpleLogin#20]
If i join into a server that runs SimpleLogin, it create and store the password but if i wanted to change the machine in which i join the server, i cannot login 'cause the password on the new machine is different from the one of the original. The only method that can solve the issue is to remove the login data of the player from the server but this is not very handy if the player cannot access the server's terminal.

[EDIT]
I saw that i can copy and paste the client file that save the password in the new client, but it isn't very handy for people that just wanted to play and are not familiar with those concepts.

**Comment by SeraphJACK** [comment]
I'm also wondering what's the solution to make machine change easier since I've received tons of complaints about it.

If SimpleLogin uses a command to register and log in, just like the plugins do, we'll lose the convenience and backward compatibility, which I don't want to.

Maybe it's a good idea to let people input a password (or randomly generate one if they prefer) when they launch their Minecraft with SimpleLogin for the first time.

Any suggestions are welcomed.

**Comment by SeraphJACK** [comment]
Added a screen to ask you to input a password (or randomly generate one) if the password is not set when trying to open Multiplayer.

**Comment by CarlosAntrax** [comment]
Hello, seeing that the post is about passwords, I would like to know if there is a way to reset the password. Since I deleted all the information from my computer, I didn't have a chance to back up the 'sl_Password' file due to lack of knowledge.
Therefore, the person in charge of the server also doesn't know exactly how it works. They already tried to delete the record using '/simplelogin cancel the registration.
Excuse me, I am using a translator; I am from Latin America. Thank you.
