### ISSUE TITLE
NoClassDefFoundError when running a server in a dev environment

### ISSUE THREAD

**Issue by przemykomo** [SeraphJACK/SimpleLogin#35]
Everything works when I run the mod on a separate server and connect to it with a client from a dev environment, however when I run both from a dev environment the server crashes with following log:
https://pastebin.com/xfne5C4k
`java.lang.NoClassDefFoundError: org/mindrot/jbcrypt/BCrypt` seems to be a shade issue perhaps?

**Comment by SeraphJACK** [comment]
Adding JBcrypt to implementation dependencies does not work.

My guess is that this is class loader related, when running the dedicated server from a production environment, loading the mod using the jar, the JBcrypt classes are loaded because we shaded them in the SimpleLogin jar file, but in the dev environment the story changes.

I really have no idea how to fix it.
