### ISSUE TITLE
Server process does not quit after stop

### ISSUE THREAD

**Issue by garsia0** [SeraphJACK/SimpleLogin#39]
the server stuck on close
 [simplelogin/]: Shutting down player login handler
[11:58:51] [Server thread/INFO] [simplelogin/]: Disabling all plugins
[11:58:51] [Server thread/INFO] [simplelogin/]: Saving all entries

and dont close
step to reproduce the issue
login into the game
close server with stop command in console
minecraft 1.16.5 forge-1.16.5-36.2.39

**Comment by SeraphJACK** [comment]
Cannot reproduce with only Simple Login installed.

This is probably caused by **other** mods who have started non-daemon threads and not shutting them down. You can investigate further by using `jstack` util:

1. Stop the server and the server freezes.
2. Use `jps` command **in another console** to find out the `PID` of the server.
3. Use `jstack -l <PID>` to list all the threads running.
4. Find the ones that have no "daemon" followed by their name.
